language: android
android:
  components:
    - tools
    - platform-tools
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
script:
  - cd AtLAS
  - gradle build connectedCheck
